# Changes here will be overwritten by Copier
_commit: v0.2.5
_src_path: gh:ninanor/python-template
author_name: JuliaWielSekiou
debug: false
default_branch_name: main
docker: false
email: julia.wiel@nina.no
notebook: true
notebook_type: jupyter
project_name: sound_recorder_calibration
project_slug: sound_recorder_calibration
repo_name: sound_recorder_calibration
repo_org: ninanor
template_type: python
type_annotations: false
